Fix Vendor Reviews Option Tabs plugin
shuup/shuup-product-reviews pull request #42
Opened 2020-11-17 14:36 UTC by robertatiriticco

- Display No Review Text in Vendor Reviews Option Tabs
- Add classes to target the Vendor Reviews Option Tabs elements
- Add Show Recommenders to Vendor Reviews Option Tabs

2020-11-17 19:51 UTC, chessbr requested changes

2020-11-17 19:51 UTC, chessbr commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +                    data-no-reviews-text="{{ _('There are no review comments.') }}"
This should be customizable. Why are you removing this feature?

2020-11-17 19:51 UTC, chessbr commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +            {{ no_reviews_text or _('There are no reviews.') }}
Maybe this deserves a new field to customize in the plugin

2020-11-18 09:42 UTC, robertatiriticco commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +                    data-no-reviews-text="{{ _('There are no review comments.') }}"
Actually "data-no-reviews-text" will never show because the plugin works so that if there are no reviews it won't display the whole tab. So it should be completely removed.

2020-11-18 11:24 UTC, chessbr commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +                    data-no-reviews-text="{{ _('There are no review comments.') }}"
But I think the point is: when there is a review but there is not a comment on that review.

2020-11-18 11:47 UTC, robertatiriticco commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +                    data-no-reviews-text="{{ _('There are no review comments.') }}"
Currently both this plugin and the Vendor comments reviews plugin are set up to show that sentence only if there are no reviews, not comment reviews. It was my mistake to not remove that "data-no-review-text" right away instead of changing it to something not proper.

This is how it currently looks like this plugin in the following cases
_There is a review with no comment:_
![image](https://user-images.githubusercontent.com/68657416/99525670-d29edf00-29a2-11eb-99d2-07b0fe59092e.png)

_There is a review with comment:_
![image](https://user-images.githubusercontent.com/68657416/99525773-f7935200-29a2-11eb-858b-ea62f1464e17.png)

_This is how it looks like the Vendor Comments Reviews_
![image](https://user-images.githubusercontent.com/68657416/99526649-35dd4100-29a4-11eb-8378-6d11cd2814c3.png)
The last one in the queue (see arrow in picture) is a review with no comment

I believe there is no need to display text when there are no comments as long as there are ratings

2020-11-18 11:49 UTC, robertatiriticco commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +                    data-no-reviews-text="{{ _('There are no review comments.') }}"
what do you think?

2020-11-18 11:50 UTC, chessbr commented on shuup_vendor_reviews/templates/shuup_vendor_reviews/plugins/vendor_reviews_option_tabs.jinja
> +                    data-no-reviews-text="{{ _('There are no review comments.') }}"
so just use the variable `no_reviews_text` with no fallback?

2020-11-18 12:00 UTC, merged